//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace .TempConvert
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.w3schools.com/xml/", ConfigurationName=".TempConvert.TempConvertSoap")]
    public interface TempConvertSoap
    {
        
        // CODEGEN: Generating message contract since element name Fahrenheit from namespace https://www.w3schools.com/xml/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/FahrenheitToCelsius", ReplyAction="*")]
        .TempConvert.FahrenheitToCelsiusResponse FahrenheitToCelsius(.TempConvert.FahrenheitToCelsiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<.TempConvert.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(.TempConvert.FahrenheitToCelsiusRequest request);
        
        // CODEGEN: Generating message contract since element name Celsius from namespace https://www.w3schools.com/xml/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/CelsiusToFahrenheit", ReplyAction="*")]
        .TempConvert.CelsiusToFahrenheitResponse CelsiusToFahrenheit(.TempConvert.CelsiusToFahrenheitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.w3schools.com/xml/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<.TempConvert.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(.TempConvert.CelsiusToFahrenheitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsius", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public .TempConvert.FahrenheitToCelsiusRequestBody Body;
        
        public FahrenheitToCelsiusRequest()
        {
        }
        
        public FahrenheitToCelsiusRequest(.TempConvert.FahrenheitToCelsiusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsiusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fahrenheit;
        
        public FahrenheitToCelsiusRequestBody()
        {
        }
        
        public FahrenheitToCelsiusRequestBody(string Fahrenheit)
        {
            this.Fahrenheit = Fahrenheit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FahrenheitToCelsiusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FahrenheitToCelsiusResponse", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public .TempConvert.FahrenheitToCelsiusResponseBody Body;
        
        public FahrenheitToCelsiusResponse()
        {
        }
        
        public FahrenheitToCelsiusResponse(.TempConvert.FahrenheitToCelsiusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsiusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FahrenheitToCelsiusResult;
        
        public FahrenheitToCelsiusResponseBody()
        {
        }
        
        public FahrenheitToCelsiusResponseBody(string FahrenheitToCelsiusResult)
        {
            this.FahrenheitToCelsiusResult = FahrenheitToCelsiusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheit", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public .TempConvert.CelsiusToFahrenheitRequestBody Body;
        
        public CelsiusToFahrenheitRequest()
        {
        }
        
        public CelsiusToFahrenheitRequest(.TempConvert.CelsiusToFahrenheitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Celsius;
        
        public CelsiusToFahrenheitRequestBody()
        {
        }
        
        public CelsiusToFahrenheitRequestBody(string Celsius)
        {
            this.Celsius = Celsius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CelsiusToFahrenheitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CelsiusToFahrenheitResponse", Namespace="https://www.w3schools.com/xml/", Order=0)]
        public .TempConvert.CelsiusToFahrenheitResponseBody Body;
        
        public CelsiusToFahrenheitResponse()
        {
        }
        
        public CelsiusToFahrenheitResponse(.TempConvert.CelsiusToFahrenheitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CelsiusToFahrenheitResult;
        
        public CelsiusToFahrenheitResponseBody()
        {
        }
        
        public CelsiusToFahrenheitResponseBody(string CelsiusToFahrenheitResult)
        {
            this.CelsiusToFahrenheitResult = CelsiusToFahrenheitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TempConvertSoapChannel : .TempConvert.TempConvertSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TempConvertSoapClient : System.ServiceModel.ClientBase<.TempConvert.TempConvertSoap>, .TempConvert.TempConvertSoap
    {
        
        public TempConvertSoapClient()
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        .TempConvert.FahrenheitToCelsiusResponse .TempConvert.TempConvertSoap.FahrenheitToCelsius(.TempConvert.FahrenheitToCelsiusRequest request)
        {
            return base.Channel.FahrenheitToCelsius(request);
        }
        
        public string FahrenheitToCelsius(string Fahrenheit)
        {
            .TempConvert.FahrenheitToCelsiusRequest inValue = new .TempConvert.FahrenheitToCelsiusRequest();
            inValue.Body = new .TempConvert.FahrenheitToCelsiusRequestBody();
            inValue.Body.Fahrenheit = Fahrenheit;
            .TempConvert.FahrenheitToCelsiusResponse retVal = ((.TempConvert.TempConvertSoap)(this)).FahrenheitToCelsius(inValue);
            return retVal.Body.FahrenheitToCelsiusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<.TempConvert.FahrenheitToCelsiusResponse> .TempConvert.TempConvertSoap.FahrenheitToCelsiusAsync(.TempConvert.FahrenheitToCelsiusRequest request)
        {
            return base.Channel.FahrenheitToCelsiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<.TempConvert.FahrenheitToCelsiusResponse> FahrenheitToCelsiusAsync(string Fahrenheit)
        {
            .TempConvert.FahrenheitToCelsiusRequest inValue = new .TempConvert.FahrenheitToCelsiusRequest();
            inValue.Body = new .TempConvert.FahrenheitToCelsiusRequestBody();
            inValue.Body.Fahrenheit = Fahrenheit;
            return ((.TempConvert.TempConvertSoap)(this)).FahrenheitToCelsiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        .TempConvert.CelsiusToFahrenheitResponse .TempConvert.TempConvertSoap.CelsiusToFahrenheit(.TempConvert.CelsiusToFahrenheitRequest request)
        {
            return base.Channel.CelsiusToFahrenheit(request);
        }
        
        public string CelsiusToFahrenheit(string Celsius)
        {
            .TempConvert.CelsiusToFahrenheitRequest inValue = new .TempConvert.CelsiusToFahrenheitRequest();
            inValue.Body = new .TempConvert.CelsiusToFahrenheitRequestBody();
            inValue.Body.Celsius = Celsius;
            .TempConvert.CelsiusToFahrenheitResponse retVal = ((.TempConvert.TempConvertSoap)(this)).CelsiusToFahrenheit(inValue);
            return retVal.Body.CelsiusToFahrenheitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<.TempConvert.CelsiusToFahrenheitResponse> .TempConvert.TempConvertSoap.CelsiusToFahrenheitAsync(.TempConvert.CelsiusToFahrenheitRequest request)
        {
            return base.Channel.CelsiusToFahrenheitAsync(request);
        }
        
        public System.Threading.Tasks.Task<.TempConvert.CelsiusToFahrenheitResponse> CelsiusToFahrenheitAsync(string Celsius)
        {
            .TempConvert.CelsiusToFahrenheitRequest inValue = new .TempConvert.CelsiusToFahrenheitRequest();
            inValue.Body = new .TempConvert.CelsiusToFahrenheitRequestBody();
            inValue.Body.Celsius = Celsius;
            return ((.TempConvert.TempConvertSoap)(this)).CelsiusToFahrenheitAsync(inValue);
        }
    }
}
